# Generated by Django 5.2.8 on 2025-11-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
